{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "b2d6c34c-c590-41d1-99c0-9d3fe222b925",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"message\": \"Starting topology monitoring\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e73, topology_type: Unknown, servers: []>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e73, topology_type: Unknown, servers: [<ServerDescription ('db', 27017) server_type: Unknown, rtt: None>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"serverHost\": \"db\", \"serverPort\": 27017, \"message\": \"Starting server monitoring\"}\n",
      "DEBUG:pymongo.connection:{\"clientId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"message\": \"Connection pool created\", \"serverHost\": \"db\", \"serverPort\": 27017}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": false, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.1173749953741208, \"reply\": \"{\\\"helloOk\\\": true, \\\"ismaster\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:24:48.748Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.connection:{\"clientId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"message\": \"Connection pool ready\", \"serverHost\": \"db\", \"serverPort\": 27017}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e73, topology_type: Unknown, servers: [<ServerDescription ('db', 27017) server_type: Unknown, rtt: None>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e73, topology_type: Single, servers: [<ServerDescription ('db', 27017) server_type: Standalone, rtt: 0.0011173749953741208>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.serverSelection:{\"message\": \"Server selection started\", \"selector\": \"<function writable_server_selector at 0xffff9c0ded40>\", \"operation\": \"update\", \"topologyDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e73, topology_type: Single, servers: [<ServerDescription ('db', 27017) server_type: Standalone, rtt: 0.0011173749953741208>]>\", \"clientId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}}\n",
      "DEBUG:pymongo.serverSelection:{\"message\": \"Server selection succeeded\", \"selector\": \"<function writable_server_selector at 0xffff9c0ded40>\", \"operation\": \"update\", \"topologyDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e73, topology_type: Single, servers: [<ServerDescription ('db', 27017) server_type: Standalone, rtt: 0.0011173749953741208>]>\", \"clientId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"serverHost\": \"db\", \"serverPort\": 27017}\n",
      "DEBUG:pymongo.connection:{\"clientId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"message\": \"Connection checkout started\", \"serverHost\": \"db\", \"serverPort\": 27017}\n",
      "DEBUG:pymongo.connection:{\"clientId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"message\": \"Connection created\", \"serverHost\": \"db\", \"serverPort\": 27017, \"driverConnectionId\": 1}\n",
      "DEBUG:pymongo.connection:{\"clientId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"message\": \"Connection ready\", \"serverHost\": \"db\", \"serverPort\": 27017, \"driverConnectionId\": 1, \"durationMS\": 0.0005053750064689666}\n",
      "DEBUG:pymongo.connection:{\"clientId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"message\": \"Connection checked out\", \"serverHost\": \"db\", \"serverPort\": 27017, \"driverConnectionId\": 1, \"durationMS\": 0.002220916998339817}\n",
      "DEBUG:pymongo.command:{\"clientId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"message\": \"Command started\", \"command\": \"{\\\"update\\\": \\\"raw_assets\\\", \\\"ordered\\\": true, \\\"lsid\\\": {\\\"id\\\": {\\\"$binary\\\": {\\\"base64\\\": \\\"UJ7C6febRAylUqBq6wKGOA==\\\", \\\"subType\\\": \\\"04\\\"}}}, \\\"$db\\\": \\\"chelle\\\", \\\"updates\\\": [{\\\"q\\\": {\\\"file_hash\\\": \\\"f0d2591e65a7e60e4c0dc5e4656a95905e4e891215cf134f61ebf6e98cdbc1f7\\\"}, \\\"u\\\": {\\\"$set\\\": {\\\"original_name\\\": \\\"Health Byte_ Product Roadmap.docx\\\", \\\"stored_name\\\": \\\"f0d2591e65a7e60e4c0dc5e4656a95905e4e891215cf134f61ebf6e98cdbc1f7.docx\\\", \\\"file_path\\\": \\\"/home/jovyan/api/filestore/raw/f0d2591e65a7e60e4c0dc5e4656a95905e4e891215cf134f61ebf6e98cdbc1f7.docx\\\", \\\"file_hash\\\": \\\"f0d2591e65a7e60e4c0dc5e4656a95905e4e891215cf134f61ebf6e98cdbc1f7\\\", \\\"file_type\\\": \\\"application/vnd.openxmlformats-officedocument.wordprocessingml.document\\\", \\\"file_size\\\": 156537, \\\"upload_date\\\": {\\\"$date\\\": \\\"2024-11-01T15:24:48.752Z\\\"}, \\\"status\\\": \\\"uploaded\\\"}}, \\\"upsert\\\": true}]}\", \"commandName\": \"update\", \"databaseName\": \"chelle\", \"requestId\": 2044897763, \"operationId\": 2044897763, \"driverConnectionId\": 1, \"serverConnectionId\": 33, \"serverHost\": \"db\", \"serverPort\": 27017}\n",
      "DEBUG:pymongo.command:{\"clientId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"message\": \"Command succeeded\", \"durationMS\": 2.06, \"reply\": \"{\\\"n\\\": 1, \\\"nModified\\\": 1, \\\"ok\\\": 1.0}\", \"commandName\": \"update\", \"databaseName\": \"chelle\", \"requestId\": 2044897763, \"operationId\": 2044897763, \"driverConnectionId\": 1, \"serverConnectionId\": 33, \"serverHost\": \"db\", \"serverPort\": 27017}\n",
      "DEBUG:pymongo.connection:{\"clientId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"message\": \"Connection checked in\", \"serverHost\": \"db\", \"serverPort\": 27017, \"driverConnectionId\": 1}\n",
      "INFO:jobs:Starting processing for file f0d2591e65a7e60e4c0dc5e4656a95905e4e891215cf134f61ebf6e98cdbc1f7\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"message\": \"Starting topology monitoring\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: []>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"message\": \"Starting server monitoring\"}\n",
      "DEBUG:pymongo.connection:{\"clientId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"message\": \"Connection pool created\", \"serverHost\": \"localhost\", \"serverPort\": 27017}\n",
      "DEBUG:pymongo.serverSelection:{\"message\": \"Server selection started\", \"selector\": \"<function writable_server_selector at 0xffff9c0ded40>\", \"operation\": \"update\", \"topologyDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None>]>\", \"clientId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}}\n",
      "DEBUG:pymongo.serverSelection:{\"message\": \"Waiting for suitable server to become available\", \"selector\": \"<function writable_server_selector at 0xffff9c0ded40>\", \"operation\": \"update\", \"topologyDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None>]>\", \"clientId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"remainingTimeMS\": 29}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.1908750020666048, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.7395000031683594, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.4041249960428104, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.542917001643218, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.9438750023255125, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.8630830018082634, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 0.49104100617114455, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.7856250051409006, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 0.9447500051464885, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.1265000066487119, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 0.7156250067055225, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.4351249992614612, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.2432910007191822, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 0.48237500595860183, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.3858749880455434, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.332208004896529, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.6337090055458248, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 2.6337500021327287, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 2.3925829882500693, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 0.6152499991003424, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10013.277172009111, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:24:58.763Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.0043329966720194, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 0.9078330040210858, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.604083998245187, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[1], line 71\u001b[0m\n\u001b[1;32m     68\u001b[0m file_hash \u001b[38;5;241m=\u001b[39m setup_test_file(test_file)\n\u001b[1;32m     70\u001b[0m \u001b[38;5;66;03m# Process with marker\u001b[39;00m\n\u001b[0;32m---> 71\u001b[0m result \u001b[38;5;241m=\u001b[39m \u001b[43mprocess_with_marker\u001b[49m\u001b[43m(\u001b[49m\u001b[43mfile_hash\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     73\u001b[0m \u001b[38;5;66;03m# Check results\u001b[39;00m\n\u001b[1;32m     74\u001b[0m asset \u001b[38;5;241m=\u001b[39m raw_assets\u001b[38;5;241m.\u001b[39mfind_one({\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mfile_hash\u001b[39m\u001b[38;5;124m'\u001b[39m: file_hash})\n",
      "File \u001b[0;32m~/api/jobs.py:194\u001b[0m, in \u001b[0;36mprocess_with_marker\u001b[0;34m(file_hash)\u001b[0m\n\u001b[1;32m    191\u001b[0m logger\u001b[38;5;241m.\u001b[39minfo(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mStarting processing for file \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mfile_hash\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m    193\u001b[0m \u001b[38;5;66;03m# Update status to processing\u001b[39;00m\n\u001b[0;32m--> 194\u001b[0m \u001b[43mupdate_asset_status\u001b[49m\u001b[43m(\u001b[49m\u001b[43mfile_hash\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mprocessing\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[1;32m    196\u001b[0m db \u001b[38;5;241m=\u001b[39m init_mongo()\n\u001b[1;32m    197\u001b[0m assets \u001b[38;5;241m=\u001b[39m db[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mraw_assets\u001b[39m\u001b[38;5;124m'\u001b[39m]\n",
      "File \u001b[0;32m~/api/jobs.py:32\u001b[0m, in \u001b[0;36mupdate_asset_status\u001b[0;34m(file_hash, status, error)\u001b[0m\n\u001b[1;32m     29\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m status \u001b[38;5;241m==\u001b[39m \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mcomplete\u001b[39m\u001b[38;5;124m'\u001b[39m:\n\u001b[1;32m     30\u001b[0m     update_data[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mprocessed_date\u001b[39m\u001b[38;5;124m'\u001b[39m] \u001b[38;5;241m=\u001b[39m datetime\u001b[38;5;241m.\u001b[39mnow()\n\u001b[0;32m---> 32\u001b[0m \u001b[43massets\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mupdate_one\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m     33\u001b[0m \u001b[43m    \u001b[49m\u001b[43m{\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mfile_hash\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[43mfile_hash\u001b[49m\u001b[43m}\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     34\u001b[0m \u001b[43m    \u001b[49m\u001b[43m{\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43m$set\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[43mupdate_data\u001b[49m\u001b[43m}\u001b[49m\n\u001b[1;32m     35\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     36\u001b[0m logger\u001b[38;5;241m.\u001b[39mdebug(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mUpdated status for \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mfile_hash\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m to \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mstatus\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m)\n",
      "File \u001b[0;32m/opt/conda/lib/python3.11/site-packages/pymongo/synchronous/collection.py:1312\u001b[0m, in \u001b[0;36mCollection.update_one\u001b[0;34m(self, filter, update, upsert, bypass_document_validation, collation, array_filters, hint, session, let, comment)\u001b[0m\n\u001b[1;32m   1308\u001b[0m common\u001b[38;5;241m.\u001b[39mvalidate_list_or_none(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124marray_filters\u001b[39m\u001b[38;5;124m\"\u001b[39m, array_filters)\n\u001b[1;32m   1310\u001b[0m write_concern \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_write_concern_for(session)\n\u001b[1;32m   1311\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m UpdateResult(\n\u001b[0;32m-> 1312\u001b[0m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_update_retryable\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m   1313\u001b[0m \u001b[43m        \u001b[49m\u001b[38;5;28;43mfilter\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1314\u001b[0m \u001b[43m        \u001b[49m\u001b[43mupdate\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1315\u001b[0m \u001b[43m        \u001b[49m\u001b[43m_Op\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mUPDATE\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1316\u001b[0m \u001b[43m        \u001b[49m\u001b[43mupsert\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1317\u001b[0m \u001b[43m        \u001b[49m\u001b[43mwrite_concern\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mwrite_concern\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1318\u001b[0m \u001b[43m        \u001b[49m\u001b[43mbypass_doc_val\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mbypass_document_validation\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1319\u001b[0m \u001b[43m        \u001b[49m\u001b[43mcollation\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mcollation\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1320\u001b[0m \u001b[43m        \u001b[49m\u001b[43marray_filters\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43marray_filters\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1321\u001b[0m \u001b[43m        \u001b[49m\u001b[43mhint\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mhint\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1322\u001b[0m \u001b[43m        \u001b[49m\u001b[43msession\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43msession\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1323\u001b[0m \u001b[43m        \u001b[49m\u001b[43mlet\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mlet\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1324\u001b[0m \u001b[43m        \u001b[49m\u001b[43mcomment\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mcomment\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1325\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m,\n\u001b[1;32m   1326\u001b[0m     write_concern\u001b[38;5;241m.\u001b[39macknowledged,\n\u001b[1;32m   1327\u001b[0m )\n",
      "File \u001b[0;32m/opt/conda/lib/python3.11/site-packages/pymongo/synchronous/collection.py:1107\u001b[0m, in \u001b[0;36mCollection._update_retryable\u001b[0;34m(self, criteria, document, operation, upsert, multi, write_concern, op_id, ordered, bypass_doc_val, collation, array_filters, hint, session, let, comment)\u001b[0m\n\u001b[1;32m   1085\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m_update\u001b[39m(\n\u001b[1;32m   1086\u001b[0m     session: Optional[ClientSession], conn: Connection, retryable_write: \u001b[38;5;28mbool\u001b[39m\n\u001b[1;32m   1087\u001b[0m ) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m Optional[Mapping[\u001b[38;5;28mstr\u001b[39m, Any]]:\n\u001b[1;32m   1088\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_update(\n\u001b[1;32m   1089\u001b[0m         conn,\n\u001b[1;32m   1090\u001b[0m         criteria,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   1104\u001b[0m         comment\u001b[38;5;241m=\u001b[39mcomment,\n\u001b[1;32m   1105\u001b[0m     )\n\u001b[0;32m-> 1107\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_database\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mclient\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_retryable_write\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m   1108\u001b[0m \u001b[43m    \u001b[49m\u001b[43m(\u001b[49m\u001b[43mwrite_concern\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;129;43;01mor\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mwrite_concern\u001b[49m\u001b[43m)\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43macknowledged\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;129;43;01mand\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[38;5;129;43;01mnot\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mmulti\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1109\u001b[0m \u001b[43m    \u001b[49m\u001b[43m_update\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1110\u001b[0m \u001b[43m    \u001b[49m\u001b[43msession\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1111\u001b[0m \u001b[43m    \u001b[49m\u001b[43moperation\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1112\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m/opt/conda/lib/python3.11/site-packages/pymongo/synchronous/mongo_client.py:1898\u001b[0m, in \u001b[0;36mMongoClient._retryable_write\u001b[0;34m(self, retryable, func, session, operation, bulk, operation_id)\u001b[0m\n\u001b[1;32m   1884\u001b[0m \u001b[38;5;250m\u001b[39m\u001b[38;5;124;03m\"\"\"Execute an operation with consecutive retries if possible\u001b[39;00m\n\u001b[1;32m   1885\u001b[0m \n\u001b[1;32m   1886\u001b[0m \u001b[38;5;124;03mReturns func()'s return value on success. On error retries the same\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   1895\u001b[0m \u001b[38;5;124;03m:param bulk: bulk abstraction to execute operations in bulk, defaults to None\u001b[39;00m\n\u001b[1;32m   1896\u001b[0m \u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[1;32m   1897\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_tmp_session(session) \u001b[38;5;28;01mas\u001b[39;00m s:\n\u001b[0;32m-> 1898\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_retry_with_session\u001b[49m\u001b[43m(\u001b[49m\u001b[43mretryable\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mfunc\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43ms\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mbulk\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43moperation\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43moperation_id\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m/opt/conda/lib/python3.11/site-packages/pymongo/synchronous/mongo_client.py:1784\u001b[0m, in \u001b[0;36mMongoClient._retry_with_session\u001b[0;34m(self, retryable, func, session, bulk, operation, operation_id)\u001b[0m\n\u001b[1;32m   1779\u001b[0m \u001b[38;5;66;03m# Ensure that the options supports retry_writes and there is a valid session not in\u001b[39;00m\n\u001b[1;32m   1780\u001b[0m \u001b[38;5;66;03m# transaction, otherwise, we will not support retry behavior for this txn.\u001b[39;00m\n\u001b[1;32m   1781\u001b[0m retryable \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mbool\u001b[39m(\n\u001b[1;32m   1782\u001b[0m     retryable \u001b[38;5;129;01mand\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39moptions\u001b[38;5;241m.\u001b[39mretry_writes \u001b[38;5;129;01mand\u001b[39;00m session \u001b[38;5;129;01mand\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m session\u001b[38;5;241m.\u001b[39min_transaction\n\u001b[1;32m   1783\u001b[0m )\n\u001b[0;32m-> 1784\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_retry_internal\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m   1785\u001b[0m \u001b[43m    \u001b[49m\u001b[43mfunc\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mfunc\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1786\u001b[0m \u001b[43m    \u001b[49m\u001b[43msession\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43msession\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1787\u001b[0m \u001b[43m    \u001b[49m\u001b[43mbulk\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mbulk\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1788\u001b[0m \u001b[43m    \u001b[49m\u001b[43moperation\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43moperation\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1789\u001b[0m \u001b[43m    \u001b[49m\u001b[43mretryable\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mretryable\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1790\u001b[0m \u001b[43m    \u001b[49m\u001b[43moperation_id\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43moperation_id\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1791\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m/opt/conda/lib/python3.11/site-packages/pymongo/_csot.py:119\u001b[0m, in \u001b[0;36mapply.<locals>.csot_wrapper\u001b[0;34m(self, *args, **kwargs)\u001b[0m\n\u001b[1;32m    117\u001b[0m         \u001b[38;5;28;01mwith\u001b[39;00m _TimeoutContext(timeout):\n\u001b[1;32m    118\u001b[0m             \u001b[38;5;28;01mreturn\u001b[39;00m func(\u001b[38;5;28mself\u001b[39m, \u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n\u001b[0;32m--> 119\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mfunc\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m/opt/conda/lib/python3.11/site-packages/pymongo/synchronous/mongo_client.py:1830\u001b[0m, in \u001b[0;36mMongoClient._retry_internal\u001b[0;34m(self, func, session, bulk, operation, is_read, address, read_pref, retryable, operation_id)\u001b[0m\n\u001b[1;32m   1793\u001b[0m \u001b[38;5;129m@_csot\u001b[39m\u001b[38;5;241m.\u001b[39mapply\n\u001b[1;32m   1794\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m_retry_internal\u001b[39m(\n\u001b[1;32m   1795\u001b[0m     \u001b[38;5;28mself\u001b[39m,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   1804\u001b[0m     operation_id: Optional[\u001b[38;5;28mint\u001b[39m] \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m,\n\u001b[1;32m   1805\u001b[0m ) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m T:\n\u001b[1;32m   1806\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124;03m\"\"\"Internal retryable helper for all client transactions.\u001b[39;00m\n\u001b[1;32m   1807\u001b[0m \n\u001b[1;32m   1808\u001b[0m \u001b[38;5;124;03m    :param func: Callback function we want to retry\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   1817\u001b[0m \u001b[38;5;124;03m    :return: Output of the calling func()\u001b[39;00m\n\u001b[1;32m   1818\u001b[0m \u001b[38;5;124;03m    \"\"\"\u001b[39;00m\n\u001b[1;32m   1819\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43m_ClientConnectionRetryable\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m   1820\u001b[0m \u001b[43m        \u001b[49m\u001b[43mmongo_client\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1821\u001b[0m \u001b[43m        \u001b[49m\u001b[43mfunc\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mfunc\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1822\u001b[0m \u001b[43m        \u001b[49m\u001b[43mbulk\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mbulk\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1823\u001b[0m \u001b[43m        \u001b[49m\u001b[43moperation\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43moperation\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1824\u001b[0m \u001b[43m        \u001b[49m\u001b[43mis_read\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mis_read\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1825\u001b[0m \u001b[43m        \u001b[49m\u001b[43msession\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43msession\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1826\u001b[0m \u001b[43m        \u001b[49m\u001b[43mread_pref\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mread_pref\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1827\u001b[0m \u001b[43m        \u001b[49m\u001b[43maddress\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43maddress\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1828\u001b[0m \u001b[43m        \u001b[49m\u001b[43mretryable\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mretryable\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1829\u001b[0m \u001b[43m        \u001b[49m\u001b[43moperation_id\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43moperation_id\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m-> 1830\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrun\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m/opt/conda/lib/python3.11/site-packages/pymongo/synchronous/mongo_client.py:2554\u001b[0m, in \u001b[0;36m_ClientConnectionRetryable.run\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   2552\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_check_last_error(check_csot\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mTrue\u001b[39;00m)\n\u001b[1;32m   2553\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m-> 2554\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_read() \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_is_read \u001b[38;5;28;01melse\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_write\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m   2555\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m ServerSelectionTimeoutError:\n\u001b[1;32m   2556\u001b[0m     \u001b[38;5;66;03m# The application may think the write was never attempted\u001b[39;00m\n\u001b[1;32m   2557\u001b[0m     \u001b[38;5;66;03m# if we raise ServerSelectionTimeoutError on the retry\u001b[39;00m\n\u001b[1;32m   2558\u001b[0m     \u001b[38;5;66;03m# attempt. Raise the original exception instead.\u001b[39;00m\n\u001b[1;32m   2559\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_check_last_error()\n",
      "File \u001b[0;32m/opt/conda/lib/python3.11/site-packages/pymongo/synchronous/mongo_client.py:2662\u001b[0m, in \u001b[0;36m_ClientConnectionRetryable._write\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   2660\u001b[0m max_wire_version \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m0\u001b[39m\n\u001b[1;32m   2661\u001b[0m is_mongos \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mFalse\u001b[39;00m\n\u001b[0;32m-> 2662\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_server \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_get_server\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m   2663\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_client\u001b[38;5;241m.\u001b[39m_checkout(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_server, \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_session) \u001b[38;5;28;01mas\u001b[39;00m conn:\n\u001b[1;32m   2664\u001b[0m     max_wire_version \u001b[38;5;241m=\u001b[39m conn\u001b[38;5;241m.\u001b[39mmax_wire_version\n",
      "File \u001b[0;32m/opt/conda/lib/python3.11/site-packages/pymongo/synchronous/mongo_client.py:2645\u001b[0m, in \u001b[0;36m_ClientConnectionRetryable._get_server\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   2640\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m_get_server\u001b[39m(\u001b[38;5;28mself\u001b[39m) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m Server:\n\u001b[1;32m   2641\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124;03m\"\"\"Retrieves a server object based on provided object context\u001b[39;00m\n\u001b[1;32m   2642\u001b[0m \n\u001b[1;32m   2643\u001b[0m \u001b[38;5;124;03m    :return: Abstraction to connect to server\u001b[39;00m\n\u001b[1;32m   2644\u001b[0m \u001b[38;5;124;03m    \"\"\"\u001b[39;00m\n\u001b[0;32m-> 2645\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_client\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_select_server\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m   2646\u001b[0m \u001b[43m        \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_server_selector\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   2647\u001b[0m \u001b[43m        \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_session\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   2648\u001b[0m \u001b[43m        \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_operation\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   2649\u001b[0m \u001b[43m        \u001b[49m\u001b[43maddress\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_address\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   2650\u001b[0m \u001b[43m        \u001b[49m\u001b[43mdeprioritized_servers\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_deprioritized_servers\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   2651\u001b[0m \u001b[43m        \u001b[49m\u001b[43moperation_id\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_operation_id\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   2652\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m/opt/conda/lib/python3.11/site-packages/pymongo/synchronous/mongo_client.py:1649\u001b[0m, in \u001b[0;36mMongoClient._select_server\u001b[0;34m(self, server_selector, session, operation, address, deprioritized_servers, operation_id)\u001b[0m\n\u001b[1;32m   1647\u001b[0m             \u001b[38;5;28;01mraise\u001b[39;00m AutoReconnect(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mserver \u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[38;5;124m:\u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[38;5;124m no longer available\u001b[39m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;241m%\u001b[39m address)  \u001b[38;5;66;03m# noqa: UP031\u001b[39;00m\n\u001b[1;32m   1648\u001b[0m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[0;32m-> 1649\u001b[0m         server \u001b[38;5;241m=\u001b[39m \u001b[43mtopology\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mselect_server\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m   1650\u001b[0m \u001b[43m            \u001b[49m\u001b[43mserver_selector\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1651\u001b[0m \u001b[43m            \u001b[49m\u001b[43moperation\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1652\u001b[0m \u001b[43m            \u001b[49m\u001b[43mdeprioritized_servers\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mdeprioritized_servers\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1653\u001b[0m \u001b[43m            \u001b[49m\u001b[43moperation_id\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43moperation_id\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1654\u001b[0m \u001b[43m        \u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m   1655\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m server\n\u001b[1;32m   1656\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m PyMongoError \u001b[38;5;28;01mas\u001b[39;00m exc:\n\u001b[1;32m   1657\u001b[0m     \u001b[38;5;66;03m# Server selection errors in a transaction are transient.\u001b[39;00m\n",
      "File \u001b[0;32m/opt/conda/lib/python3.11/site-packages/pymongo/synchronous/topology.py:398\u001b[0m, in \u001b[0;36mTopology.select_server\u001b[0;34m(self, selector, operation, server_selection_timeout, address, deprioritized_servers, operation_id)\u001b[0m\n\u001b[1;32m    388\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mselect_server\u001b[39m(\n\u001b[1;32m    389\u001b[0m     \u001b[38;5;28mself\u001b[39m,\n\u001b[1;32m    390\u001b[0m     selector: Callable[[Selection], Selection],\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    395\u001b[0m     operation_id: Optional[\u001b[38;5;28mint\u001b[39m] \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m,\n\u001b[1;32m    396\u001b[0m ) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m Server:\n\u001b[1;32m    397\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124;03m\"\"\"Like select_servers, but choose a random server if several match.\"\"\"\u001b[39;00m\n\u001b[0;32m--> 398\u001b[0m     server \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_select_server\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    399\u001b[0m \u001b[43m        \u001b[49m\u001b[43mselector\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    400\u001b[0m \u001b[43m        \u001b[49m\u001b[43moperation\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    401\u001b[0m \u001b[43m        \u001b[49m\u001b[43mserver_selection_timeout\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    402\u001b[0m \u001b[43m        \u001b[49m\u001b[43maddress\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    403\u001b[0m \u001b[43m        \u001b[49m\u001b[43mdeprioritized_servers\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    404\u001b[0m \u001b[43m        \u001b[49m\u001b[43moperation_id\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43moperation_id\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    405\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    406\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m _csot\u001b[38;5;241m.\u001b[39mget_timeout():\n\u001b[1;32m    407\u001b[0m         _csot\u001b[38;5;241m.\u001b[39mset_rtt(server\u001b[38;5;241m.\u001b[39mdescription\u001b[38;5;241m.\u001b[39mmin_round_trip_time)\n",
      "File \u001b[0;32m/opt/conda/lib/python3.11/site-packages/pymongo/synchronous/topology.py:376\u001b[0m, in \u001b[0;36mTopology._select_server\u001b[0;34m(self, selector, operation, server_selection_timeout, address, deprioritized_servers, operation_id)\u001b[0m\n\u001b[1;32m    367\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m_select_server\u001b[39m(\n\u001b[1;32m    368\u001b[0m     \u001b[38;5;28mself\u001b[39m,\n\u001b[1;32m    369\u001b[0m     selector: Callable[[Selection], Selection],\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    374\u001b[0m     operation_id: Optional[\u001b[38;5;28mint\u001b[39m] \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m,\n\u001b[1;32m    375\u001b[0m ) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m Server:\n\u001b[0;32m--> 376\u001b[0m     servers \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mselect_servers\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    377\u001b[0m \u001b[43m        \u001b[49m\u001b[43mselector\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43moperation\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mserver_selection_timeout\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43maddress\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43moperation_id\u001b[49m\n\u001b[1;32m    378\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    379\u001b[0m     servers \u001b[38;5;241m=\u001b[39m _filter_servers(servers, deprioritized_servers)\n\u001b[1;32m    380\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mlen\u001b[39m(servers) \u001b[38;5;241m==\u001b[39m \u001b[38;5;241m1\u001b[39m:\n",
      "File \u001b[0;32m/opt/conda/lib/python3.11/site-packages/pymongo/synchronous/topology.py:283\u001b[0m, in \u001b[0;36mTopology.select_servers\u001b[0;34m(self, selector, operation, server_selection_timeout, address, operation_id)\u001b[0m\n\u001b[1;32m    280\u001b[0m     server_timeout \u001b[38;5;241m=\u001b[39m server_selection_timeout\n\u001b[1;32m    282\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_lock:\n\u001b[0;32m--> 283\u001b[0m     server_descriptions \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_select_servers_loop\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    284\u001b[0m \u001b[43m        \u001b[49m\u001b[43mselector\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mserver_timeout\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43moperation\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43moperation_id\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43maddress\u001b[49m\n\u001b[1;32m    285\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    287\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m [\n\u001b[1;32m    288\u001b[0m         cast(Server, \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mget_server_by_address(sd\u001b[38;5;241m.\u001b[39maddress)) \u001b[38;5;28;01mfor\u001b[39;00m sd \u001b[38;5;129;01min\u001b[39;00m server_descriptions\n\u001b[1;32m    289\u001b[0m     ]\n",
      "File \u001b[0;32m/opt/conda/lib/python3.11/site-packages/pymongo/synchronous/topology.py:357\u001b[0m, in \u001b[0;36mTopology._select_servers_loop\u001b[0;34m(self, selector, timeout, operation, operation_id, address)\u001b[0m\n\u001b[1;32m    351\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_request_check_all()\n\u001b[1;32m    353\u001b[0m \u001b[38;5;66;03m# Release the lock and wait for the topology description to\u001b[39;00m\n\u001b[1;32m    354\u001b[0m \u001b[38;5;66;03m# change, or for a timeout. We won't miss any changes that\u001b[39;00m\n\u001b[1;32m    355\u001b[0m \u001b[38;5;66;03m# came after our most recent apply_selector call, since we've\u001b[39;00m\n\u001b[1;32m    356\u001b[0m \u001b[38;5;66;03m# held the lock until now.\u001b[39;00m\n\u001b[0;32m--> 357\u001b[0m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_condition\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mwait\u001b[49m\u001b[43m(\u001b[49m\u001b[43mcommon\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mMIN_HEARTBEAT_INTERVAL\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    358\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_description\u001b[38;5;241m.\u001b[39mcheck_compatible()\n\u001b[1;32m    359\u001b[0m now \u001b[38;5;241m=\u001b[39m time\u001b[38;5;241m.\u001b[39mmonotonic()\n",
      "File \u001b[0;32m/opt/conda/lib/python3.11/threading.py:331\u001b[0m, in \u001b[0;36mCondition.wait\u001b[0;34m(self, timeout)\u001b[0m\n\u001b[1;32m    329\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m    330\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m timeout \u001b[38;5;241m>\u001b[39m \u001b[38;5;241m0\u001b[39m:\n\u001b[0;32m--> 331\u001b[0m         gotit \u001b[38;5;241m=\u001b[39m \u001b[43mwaiter\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43macquire\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43;01mTrue\u001b[39;49;00m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtimeout\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    332\u001b[0m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m    333\u001b[0m         gotit \u001b[38;5;241m=\u001b[39m waiter\u001b[38;5;241m.\u001b[39macquire(\u001b[38;5;28;01mFalse\u001b[39;00m)\n",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m: "
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.155124991782941, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10002.791837992845, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:25:08.769Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 2.1455829992191866, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10008.864921008353, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:25:18.784Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.5282090025721118, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10007.33058800688, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:25:28.794Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.1777089966926724, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10008.434670991846, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:25:38.805Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 2.202832998591475, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10006.841171009, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:25:48.822Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.8939580040751025, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10014.341130008688, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:25:58.839Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 0.7448750111507252, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10010.95429599809, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:26:08.853Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.0088340059155598, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10015.806046008947, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:26:18.870Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.850625005317852, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10011.340088996803, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:26:28.886Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.4241249882616103, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10014.173629999277, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:26:38.903Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.8929170037154108, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10009.586379004759, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:26:48.915Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 2.5004170020110905, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10002.74558798992, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:26:58.924Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 0.9999579924624413, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10008.874671999365, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:27:08.937Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.3962090015411377, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10004.710794994025, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:27:18.945Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.8313750042580068, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10001.530671986984, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:27:28.954Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 2.3939170059747994, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10007.05992199073, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:27:38.969Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.3188750017434359, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10006.614212004934, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:27:48.980Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.3365000049816445, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10009.418671994354, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:27:58.993Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 0.4119589866604656, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10010.648838011548, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:28:09.005Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 2.474042004905641, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10001.417419989593, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:28:19.012Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.542665995657444, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10009.790587995667, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:28:29.028Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 2.140041993698105, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10008.526088000508, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:28:39.040Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.6546249971725047, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10010.34567100578, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:28:49.051Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.1092500062659383, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10003.986255003838, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:28:59.062Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 2.422207995550707, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10006.64721299836, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:29:09.075Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 0.8613750105723739, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10010.976503996062, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:29:19.088Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 0.9065830090548843, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 9997.87554598879, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:29:29.100Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.6236670053331181, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10009.556504999637, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:29:39.112Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 3.7732500059064478, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10012.469837995013, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:29:49.127Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.847291990998201, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 9998.32454600255, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:29:59.142Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 0.9645419922890142, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10012.75317100226, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:30:09.157Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.292625005589798, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10013.368795989663, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:30:19.174Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.2560830073198304, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10014.155754994135, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:30:29.190Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 2.9647500050486997, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10002.617837992148, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:30:39.208Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.1856670025736094, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10009.173671001918, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:30:49.219Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 0.7989169971551746, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10012.257378999493, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:30:59.235Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 0.6954159907763824, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10008.1143790012, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:31:09.247Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.7265420028707013, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10010.657587001333, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:31:19.260Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.1484999995445833, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10014.995213001384, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:31:29.277Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 4.059500002767891, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 9998.912046998157, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:31:39.293Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.0592080070637167, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10010.356171012972, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:31:49.306Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.0057079925900325, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10008.278046996566, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:31:59.318Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.5069169894559309, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10000.258796004346, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:32:09.322Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 0.5836250056745484, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 10014.516711991746, \"reply\": \"{\\\"isWritablePrimary\\\": true, \\\"topologyVersion\\\": {\\\"processId\\\": {\\\"$oid\\\": \\\"6724f21d82e6cdec57b3651a\\\"}}, \\\"maxBsonObjectSize\\\": 16777216, \\\"maxMessageSizeBytes\\\": 48000000, \\\"maxWriteBatchSize\\\": 100000, \\\"localTime\\\": {\\\"$date\\\": \\\"2024-11-01T15:32:19.339Z\\\"}, \\\"logicalSessionTimeoutMinutes\\\": 30, \\\"connectionId\\\": 31, \\\"maxWireVersion\\\": 25, \\\"ok\\\": 1.0}\", \"message\": \"Server heartbeat succeeded\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"driverConnectionId\": 1, \"serverConnectionId\": 31, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"message\": \"Server heartbeat started\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"serverHost\": \"localhost\", \"serverPort\": 27017, \"awaited\": false, \"durationMS\": 1.934667001478374, \"failure\": \"\\\"AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\\\"\", \"message\": \"Server heartbeat failed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e74\"}, \"previousDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"newDescription\": \"<TopologyDescription id: 6724f2c0a8704f1f0cbd0e74, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\", \"message\": \"Topology description changed\"}\n",
      "DEBUG:pymongo.topology:{\"topologyId\": {\"$oid\": \"6724f2c0a8704f1f0cbd0e73\"}, \"serverHost\": \"db\", \"serverPort\": 27017, \"awaited\": true, \"durationMS\": 8069.014836990391, \"failure\": \"\\\"_OperationCancelled('operation cancelled')\\\"\", \"message\": \"Server heartbeat failed\"}\n"
     ]
    }
   ],
   "source": [
    "# First, set up imports and paths\n",
    "import sys\n",
    "import os\n",
    "\n",
    "sys.path.append(\"/home/jovyan/api\")  # Add api directory to Python path\n",
    "\n",
    "from jobs import process_with_marker\n",
    "import hashlib\n",
    "from datetime import datetime\n",
    "from pymongo import MongoClient\n",
    "\n",
    "# Connect to MongoDB\n",
    "client = MongoClient(\"mongodb://db:27017/\")\n",
    "db = client[\"chelle\"]\n",
    "raw_assets = db[\"raw_assets\"]\n",
    "\n",
    "\n",
    "# Function to simulate file upload and create asset record\n",
    "def setup_test_file(file_path: str):\n",
    "    # Read file and calculate hash\n",
    "    with open(file_path, \"rb\") as f:\n",
    "        content = f.read()\n",
    "        file_hash = hashlib.sha256(content).hexdigest()\n",
    "\n",
    "    # Get file details\n",
    "    filename = os.path.basename(file_path)\n",
    "    file_size = len(content)\n",
    "    file_ext = os.path.splitext(filename)[1].lower()\n",
    "\n",
    "    # Determine mime type\n",
    "    mime_types = {\n",
    "        \".pdf\": \"application/pdf\",\n",
    "        \".docx\": \"application/vnd.openxmlformats-officedocument.wordprocessingml.document\",\n",
    "    }\n",
    "    file_type = mime_types.get(file_ext, \"application/octet-stream\")\n",
    "\n",
    "    # Save file to filestore\n",
    "    raw_dir = \"/home/jovyan/api/filestore/raw\"\n",
    "    os.makedirs(raw_dir, exist_ok=True)\n",
    "    stored_filename = f\"{file_hash}{file_ext}\"\n",
    "    stored_path = os.path.join(raw_dir, stored_filename)\n",
    "\n",
    "    with open(stored_path, \"wb\") as f:\n",
    "        f.write(content)\n",
    "\n",
    "    # Create asset record\n",
    "    asset_record = {\n",
    "        \"original_name\": filename,\n",
    "        \"stored_name\": stored_filename,\n",
    "        \"file_path\": stored_path,\n",
    "        \"file_hash\": file_hash,\n",
    "        \"file_type\": file_type,\n",
    "        \"file_size\": file_size,\n",
    "        \"upload_date\": datetime.now(),\n",
    "        \"status\": \"uploaded\",\n",
    "        \"processed\": False,\n",
    "    }\n",
    "\n",
    "    # Insert or update record\n",
    "    raw_assets.update_one({\"file_hash\": file_hash}, {\"$set\": asset_record}, upsert=True)\n",
    "\n",
    "    return file_hash\n",
    "\n",
    "\n",
    "# Test with a file\n",
    "test_file = \"/home/jovyan/nb/Health Byte_ Product Roadmap.docx\"  # Replace with your test file path\n",
    "file_hash = setup_test_file(test_file)\n",
    "\n",
    "# Process with marker\n",
    "result = process_with_marker(file_hash)\n",
    "\n",
    "# Check results\n",
    "asset = raw_assets.find_one({\"file_hash\": file_hash})\n",
    "print(\"Status:\", asset.get(\"status\"))\n",
    "print(\"Processed:\", asset.get(\"processed\"))\n",
    "print(\"Processing details:\", asset.get(\"processing_details\"))\n",
    "\n",
    "# If processed successfully, check the extracted content\n",
    "if asset.get(\"processed\"):\n",
    "    processed_paths = asset.get(\"processed_paths\", {})\n",
    "\n",
    "    # Check markdown content\n",
    "    if \"markdown\" in processed_paths:\n",
    "        with open(processed_paths[\"markdown\"], \"r\") as f:\n",
    "            print(\"\\nFirst 500 characters of markdown content:\")\n",
    "            print(f.read(500))\n",
    "\n",
    "    # Check images\n",
    "    if \"images\" in processed_paths:\n",
    "        print(\"\\nExtracted images:\")\n",
    "        for img_name, img_path in processed_paths[\"images\"].items():\n",
    "            print(f\"- {img_name}: {img_path}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "4545a416-5208-4b6f-a28f-a6f964f076c3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Found existing installation: PyMuPDF 1.24.13\n",
      "Uninstalling PyMuPDF-1.24.13:\n",
      "  Successfully uninstalled PyMuPDF-1.24.13\n",
      "Collecting PyMuPDF==1.22.0\n",
      "  Downloading PyMuPDF-1.22.0-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (8.3 kB)\n",
      "Downloading PyMuPDF-1.22.0-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (14.1 MB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m14.1/14.1 MB\u001b[0m \u001b[31m52.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0ma \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hInstalling collected packages: PyMuPDF\n",
      "Successfully installed PyMuPDF-1.22.0\n"
     ]
    }
   ],
   "source": [
    "!pip uninstall PyMuPDF -y\n",
    "!pip install PyMuPDF==1.22.0"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "37d1e8e4-0e64-4e30-a3ba-c1ad4728399e",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
